apiVersion: v2
name: wordpress
version: v0.1.0
# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A chart for deploying Wordpress. Used to help learn Helm.
type: application
keywords:
  - Wordpress
  - Learning
  - Simple
home: https://github.com/kclapper/wordpress-chart
sources:
  - https://github.com/kclapper/wordpress-chart
# dependencies: # A list of the chart requirements (optional)
#   - name: The name of the chart (nginx)
#     version: The version of the chart ("1.2.3")
#     repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
#     condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
#     tags: # (optional)
#       - Tags can be used to group charts for enabling/disabling together
#     import-values: # (optional)
#       - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
# annotations:
#   example: A list of annotations keyed by name (optional).