---
# Database login
apiVersion: v1
kind: Secret
metadata:
  name: database-login
type: kubernetes.io/basic-auth
stringData:
  username: "{{ randAlphaNum 32 | b64enc }}"
  password: "{{ randAlphaNum 32 | b64enc }}"