---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: "{{ .Release.Name }}-wordpress"
          image: "wordpress:{{ .Values.wordpress.version }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "250Mi"
              cpu: "250m"
            requests:
              memory: "20Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Release.Name }}-mariadb"
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-login
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-login
                  key: password
            - name: WORDPRESS_DB_NAME
              value: "{{ .Release.Name }}-database"

---
kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-wordpress"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "wordpress"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-wordpress"
spec:
  rules:
  - http:
      paths:
      - path: "/" 
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-wordpress"
            port:
              number: 80 
